config/routes.rb
module CategoryTree
  Engine.routes.draw do
    resources :categories, :as => :categories
  end
end

app/models/category_tree/category.rb
module CategoryTree
  class Category < ActiveRecord::Base
    has_ancestry :orphan_strategy => :restrict, :cache_depth => true
    mount_uploader :icon, IconUploader

    validates :name, :presence => true, :uniqueness => true
    validates :icon, :presence => true

    scope :search, (lambda do |search_keys|
      if search_keys
        search_keys.gsub!(' ', '%')
        where_clause = 'LOWER(CAST(code AS text)) LIKE LOWER(:search) OR ' \
                       'LOWER(name) LIKE LOWER(:search)'
        where(where_clause, :search => "%#{search_keys}%")
      end
    end)

    def breadcrumbs
      names = ancestors.map(&:name)
      names << name
      names.join(' > ')
    end
  end
end

app/controllers/category_tree/api/categories_controller.rb
module CategoryTree
  class Api::CategoriesController < ApplicationController
    def index
      @categories = Category.order(:name)
      @categories = @categories.search(params[:term]) if params[:term].present?
    end

    def show
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/category_tree/application_controller.rb
module CategoryTree
  class ApplicationController < ActionController::Base
  end
end

app/controllers/category_tree/categories_controller.rb
# require_dependency "category_tree/application_controller"

module CategoryTree
  class CategoriesController < CategoryTree::ApplicationController
    before_action :set_category, :only => [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      @categories = Category.roots
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
      @category.parent_id = params[:id] if params[:id].present?
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, :notice => 'Category was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, :notice => 'Category was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, :notice => 'Category was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:code,
                                       :name,
                                       :parent_id,
                                       :icon,
                                       :icon_cache)
    end
  end
end

app/views/category_tree/categories/_form.html.haml
= form.input :name
= form.input :parent_name, :as => :independent, :input_html => {:data => {:"autocomplete-source" => api_categories_path}, :value => @category.parent ? @category.parent.name : ''}, :label => 'Parent'
= form.input :parent_id, :as => :hidden
= image_tag @category.icon.url if @category.icon?
= form.input :icon, :as => :file
= form.input :icon_cache, :as => :hidden

= form.button :submit
\|
= link_to 'Cancel', cancel_url

app/views/category_tree/categories/_table.html.haml
%table
  %thead
    %tr
      %th Code
      %th Name
  %tbody
    - categories.each do |category|
      %tr
        %td= link_to category.code, category_path(category)
        %td= category.name

app/views/category_tree/categories/edit.html.haml
%h1 Editing category

= simple_form_for @category, :url => category_path(@category), :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :cancel_url => category_path(@category)

app/views/category_tree/categories/index.html.haml
%h1 Listing categories

= render :partial => 'table', :locals => {:categories => @categories}

%br

app/views/category_tree/categories/new.html.haml
%h1 New category

= simple_form_for @category, :url => categories_path, :html => { :class => 'form' } do |form|
  = render 'form', :form => form, :cancel_url => categories_path

app/views/category_tree/categories/show.html.haml
%dl
  %dt Code:
  %dd
    = @category.code
%dl
  %dt Name:
  %dd
    = @category.name

%dl
  %dt Full Icon:
  %dd
    = image_tag @category.icon.full.url

%dl
  %dt Small Icon:
  %dd
    = image_tag @category.icon.thumb.url

-if @category.parent
  %dl
    %dt Parent:
    %dd
      = link_to @category.parent.name, category_path(@category.parent)

- if @category.has_children?
  %dl
    %dt Children:
    %dd
      = render :partial => 'table', :locals => {:categories => @category.children}

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', @category.parent ? category_path(@category.parent) : categories_path

app/views/layouts/category_tree/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CategoryTree</title>
  <%= stylesheet_link_tag    "category_tree/application", media: "all" %>
  <%= javascript_include_tag "category_tree/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>